---

- name: PHP | Gather server Package information
  package_facts:
    manager: "auto"

- name: dump
  debug:
    var: ansible_distribution

- name: dump
  debug:
    var: ansible_os_family

- name: dump
  debug:
    var: ansible_distribution_major_version

- name: PHP | Include OS variables
  include_vars: '{{ ansible_os_family }}.yml'

- name: PHP | Include OS installation
  include_tasks: '{{ ansible_os_family }}.yml'
