---

php74:
  packages:
    - php7.4
    - php7.4-cli
    - php7.4-common
    - php7.4-zip
    - php7.4-xml
    - php7.4-mysqlnd
    - php7.4-gd
    - php7.4-soap
    - php7.4-imap
    - php7.4-mbstring
    - php7.4-intl
    - php7.4-json
    - php7.4-pdo
  fpm:
    fpmUser: "{{ webService }}"
    fpmGroup: "{{ webService }}"
    fpmListenOwner: "{{ webService }}"
    fpmListenGroup: "{{ webService }}"
    fpmListenMode: "0660"
    fpmSock: /var/run/php74-fpm.sock
    fpmListenAllowedClients: 127.0.0.1
    fpmStatusPath: "/status"
    fpmSlowLog: "{{ fpmPhp74LogLocation }}www-slow.log"
    fpmErrorLog: "{{ fpmPhp74LogLocation}}www-error.log"
    fpmSessionSaveHandler: files
    fpmSessionsavePath: /opt/remi/php74/root/var/lib/php/session
    fpmSessionSaveCache: /opt/remi/php74/root/var/lib/php/wsdlcache
  default: true
