---

php80:
  packages:
    - php8.0
    - php8.0-cli
    - php8.0-common
    - php8.0-fpm
    - php8.0-gd
    - php8.0-intl
    - php8.0-bcmath
    - php8.0-opcache
    - php8.0-pdo
    - php8.0-mysqlnd
    - php8.0-zip
    - php8.0-xml
    - php8.0-soap
    - php8.0-imap
    - php8.0-mbstring
  fpm:
    fpmUser: "{{ webService|default('ansible') }}"
    fpmGroup: "{{ webService|default('ansible') }}"
    fpmListenOwner: "{{ webService|default('ansible') }}"
    fpmListenGroup: "{{ webService|default('ansible') }}"
    fpmListenMode: "0660"
    fpmSock: /var/run/php80-fpm.sock
    fpmListenAllowedClients: 127.0.0.1
    fpmStatusPath: "/status"
    fpmSlowLog: "{{ fpmPhp80LogLocation }}www-slow.log"
    fpmErrorLog: "{{ fpmPhp80LogLocation}}www-error.log"
    fpmSessionSaveHandler: files
    fpmSessionsavePath: /opt/remi/php80/root/var/lib/php/session
    fpmSessionSaveCache: /opt/remi/php80/root/var/lib/php/wsdlcache
  default: true
