---
- name: Converge
  hosts: all
  become: true

  vars:
    webService: "httpd"

  roles:
    - role: ggiinnoo.remi_repo
    - role: ggiinnoo.webserver
      version: 1.0.0
    - ansible-role-php
