---
- name: Converge
  hosts: all
  become: true

  vars_files:
    - "{{ ansible_os_family }}-php-70.yml"

  vars:
    webService: "httpd"

  roles:
    - role: ggiinnoo.remi_repo
      when: ansible_os_family == 'RedHat'
    - role: ggiinnoo.webserver
      version: 1.0.0
    - ansible-role-php
