---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - include_vars: "{{ ansible_os_family }}-php-81.yml"

  roles:
    - role: ggiinnoo.remi_repo
      when: ansible_os_family == 'RedHat'
    - ansible-role-php
