---

- name: PHP | Debian | Create folder
  file:
    mode: "0755"
    path: "{{ phpDebianCGIBinLocation }}"
    state: "directory"

- name: PHP | Debian | Create nginx user
  user:
    name: nginx
    shell: /bin/false

- name: PHP | Debian | Install required packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - "{{ phpDebianPackages }}"

- name: PHP | Debian | Place php repo file
  template:
    src: "{{ phpDebianRepoSource }}"
    dest: "{{ phpDebianRepoDestination }}"
  when: ansible_distribution == 'Debian'

- name: PHP | Debian | Get GPG key
  get_url:
    url: "{{ phpDebianGPGKeyUrl }}"
    dest: "{{ phpDebianGPGKeyLocation }}"
  when: ansible_distribution == 'Debian'

- name: PHP | Debian | Install GPG Key
  shell: "gpg --quiet --import --import-options import-show {{ phpDebianGPGKeyLocation }}"
  register: phpDebianGpgInstall
  changed_when: phpDebianGpgInstall.rc != 0
  when: ansible_distribution == 'Debian'

- name: PHP | Ubuntu | Place php repo file
  apt_repository:
    repo: "{{ phpUbuntuRepoName }}"
    state: "{{ phpUbuntuRepoState }}"
  when: ansible_distribution == 'Ubuntu'

- name: PHP | Debian | Generate full list to install
  set_fact:
    phpItems: "{{ php54.packages|default([]) + php55.packages|default([]) + php56.packages|default([]) + php70.packages|default([]) + php71.packages|default([]) + php72.packages|default([]) + php73.packages|default([]) + php74.packages|default([]) + php80.packages|default([]) + php81.packages|default([])}}"

- name: PHP | Debian | Install php items
  apt:
    name: "{{ phpItems }}"
    state: "present"
    update_cache: true
