---


# setup/config fpm
- name: php 56 template's
  template:
    dest: "{{ item.dest }}"
    src: "{{ item.src }}"
  loop:
    - {src: "{{ fpmConfLocationTemplate56 }}", dest: "{{ phpRedHatFpmConfLocation56 }}"}
    - {src: "{{ phpiniConfLocationTemplate56 }}", dest: "{{ phpRedHatPhpiniConfLocation56 }}"}
    - {src: "{{ fpmWrapperLocationTemplate56 }}", dest: "{{ phpRedHatFpmWrapperLocation56 }}"}
  when: php56 is defined
  notify: RedHatphp56Service
  loop_control:
    label: "Placing template: '{{ item.src }}' at: '{{ item.dest }}' "

- name: php 70 template's
  template:
    dest: "{{ item.dest }}"
    src: "{{ item.src }}"
  loop:
    - {src: "{{ fpmConfLocationTemplate70 }}", dest: "{{ phpRedHatFpmConfLocation70 }}"}
    - {src: "{{ phpiniConfLocationTemplate70 }}", dest: "{{ phpRedHatPhpiniConfLocation70 }}"}
    - {src: "{{ fpmWrapperLocationTemplate70 }}", dest: "{{ phpRedHatFpmWrapperLocation70 }}"}
  when: php70 is defined
  notify: RedHatphp70Service
  loop_control:
    label: "Placing template: '{{ item.src }}' at: '{{ item.dest }}' "

- name: php 71 template's
  template:
    dest: "{{ item.dest }}"
    src: "{{ item.src }}"
  loop:
    - {src: "{{ fpmConfLocationTemplate71 }}", dest: "{{ phpRedHatFpmConfLocation71 }}"}
    - {src: "{{ phpiniConfLocationTemplate71 }}", dest: "{{ phpRedHatPhpiniConfLocation71 }}"}
    - {src: "{{ fpmWrapperLocationTemplate71 }}", dest: "{{ phpRedHatFpmWrapperLocation71 }}"}
  when: php71 is defined
  notify: RedHatphp71Service
  loop_control:
    label: "Placing template: '{{ item.src }}' at: '{{ item.dest }}' "

- name: php 72 template's
  template:
    dest: "{{ item.dest }}"
    src: "{{ item.src }}"
  loop:
    - {src: "{{ fpmConfLocationTemplate72 }}", dest: "{{ phpRedHatFpmConfLocation72 }}"}
    - {src: "{{ phpiniConfLocationTemplate72 }}", dest: "{{ phpRedHatPhpiniConfLocation72 }}"}
    - {src: "{{ fpmWrapperLocationTemplate72 }}", dest: "{{ phpRedHatFpmWrapperLocation72 }}"}
  when: php72 is defined
  notify: RedHatphp72Service
  loop_control:
    label: "Placing template: '{{ item.src }}' at: '{{ item.dest }}' "

- name: php 73 template's
  template:
    dest: "{{ item.dest }}"
    src: "{{ item.src }}"
  loop:
    - {src: "{{ fpmConfLocationTemplate73 }}", dest: "{{ phpRedHatFpmConfLocation73 }}"}
    - {src: "{{ phpiniConfLocationTemplate73 }}", dest: "{{ phpRedHatPhpiniConfLocation73 }}"}
    - {src: "{{ fpmWrapperLocationTemplate73 }}", dest: "{{ phpRedHatFpmWrapperLocation73 }}"}
  when: php73 is defined
  notify: RedHatphp73Service
  loop_control:
    label: "Placing template: '{{ item.src }}' at: '{{ item.dest }}' "

- name: php 74 template's
  template:
    dest: "{{ item.dest }}"
    src: "{{ item.src }}"
  loop:
    - {src: "{{ fpmConfLocationTemplate74 }}", dest: "{{ phpRedHatFpmConfLocation74 }}"}
    - {src: "{{ phpiniConfLocationTemplate74 }}", dest: "{{ phpRedHatPhpiniConfLocation74 }}"}
    - {src: "{{ fpmWrapperLocationTemplate74 }}", dest: "{{ phpRedHatFpmWrapperLocation74 }}"}
  when: php74 is defined
  notify: RedHatphp74Service
  loop_control:
    label: "Placing template: '{{ item.src }}' at: '{{ item.dest }}' "

- name: php 80 template's
  template:
    dest: "{{ item.dest }}"
    src: "{{ item.src }}"
  loop:
    - {src: "{{ fpmConfLocationTemplate80 }}", dest: "{{ phpRedHatFpmConfLocation80 }}"}
    - {src: "{{ phpiniConfLocationTemplate80 }}", dest: "{{ phpRedHatPhpiniConfLocation80 }}"}
    - {src: "{{ fpmWrapperLocationTemplate80 }}", dest: "{{ phpRedHatFpmWrapperLocation80 }}"}
  when: php80 is defined
  notify: RedHatphp80Service
  loop_control:
    label: "Placing template: '{{ item.src }}' at: '{{ item.dest }}' "

- name: php 81 template's
  template:
    dest: "{{ item.dest }}"
    src: "{{ item.src }}"
  loop:
    - {src: "{{ fpmConfLocationTemplate81 }}", dest: "{{ phpRedHatFpmConfLocation81 }}"}
    - {src: "{{ phpiniConfLocationTemplate81 }}", dest: "{{ phpRedHatPhpiniConfLocation81 }}"}
    - {src: "{{ fpmWrapperLocationTemplate81 }}", dest: "{{ phpRedHatFpmWrapperLocation81 }}"}
  when: php81 is defined
  notify: RedHatphp81Service
  loop_control:
    label: "Placing template: '{{ item.src }}' at: '{{ item.dest }}' "

- name: php 82 template's
  template:
    dest: "{{ item.dest }}"
    src: "{{ item.src }}"
  loop:
    - {src: "{{ fpmConfLocationTemplate82 }}", dest: "{{ phpRedHatFpmConfLocation82 }}"}
    - {src: "{{ phpiniConfLocationTemplate82 }}", dest: "{{ phpRedHatPhpiniConfLocation82 }}"}
    - {src: "{{ fpmWrapperLocationTemplate82 }}", dest: "{{ phpRedHatFpmWrapperLocation82 }}"}
  when: php82 is defined
  notify: RedHatphp82Service
  loop_control:
    label: "Placing template: '{{ item.src }}' at: '{{ item.dest }}' "

# Include user config
- name: Include user config
  include_tasks: user.yml
  when:
    - Users is defined

# script wrapper files permissions
- name: Set permissions wrapper script's
  file:
    path: "{{ phpRedHatCGIBinLocation }}"
    mode: "0755"
    recurse: "true"
    state: "directory"

# php conf tempalte for apache
- name: Apache php.conf file
  template:
    dest: "{{ httpdPHPConfLocation }}"
    src: "{{ httpdPHPConfLocationTemplate }}"
  when:
    - webService|default("") == "httpd" and phpRedHatNginxPackageName not in ansible_facts.packages

# php conf template for nginx
- name: PHP | RedHat | Nginx php.conf file
  template:
    dest: "{{ nginxPHPConfLocation }}"
    src: "{{ nginxPHPConfLocationTemplate }}"
  when:
    - webService|default("") == "nginx" and phpRedHatApachePackageName not in ansible_facts.packages

# set default php version for cli use
- name: PHP | RedHat | Set default php version
  file:
    src: "{{ item.src }}"
    path: "{{ item.dest }}"
    state: "link"
  loop:
    - {src: "/opt/remi/php{{ phpVersionDefault }}/root/usr/bin/php", dest: "/usr/bin/php"}
    - {src: "/opt/remi/php{{ phpVersionDefault }}/root/usr/bin/php-cgi", dest: "/usr/bin/php-cgi"}
    - {src: "/opt/remi/php{{ phpVersionDefault }}/root/usr/bin/pear", dest: "/usr/bin/php-pear"}
    - {src: "/opt/remi/php{{ phpVersionDefault }}/root/usr/bin/phar.phar", dest: "/usr/bin/php-phar"}
  when: phpVersionDefault is defined

- name: PHP | RedHat | Create log directories httpd
  file:
    group: "apache"
    owner: "apache"
    mode: "0755"
    path: "{{ item }}"
    state: "directory"
  with_items:
    - "{{ fpmPhp56LogLocation }}"
    - "{{ fpmPhp70LogLocation }}"
    - "{{ fpmPhp71LogLocation }}"
    - "{{ fpmPhp72LogLocation }}"
    - "{{ fpmPhp73LogLocation }}"
    - "{{ fpmPhp74LogLocation }}"
    - "{{ fpmPhp80LogLocation }}"
    - "{{ fpmPhp81LogLocation }}"
    - "{{ fpmPhp82LogLocation }}"
  when: webService|default("") == "httpd"

- name: PHP | RedHat | Create php session folder httpd
  file:
    group: "apache"
    owner: "apache"
    mode: "0755"
    path: "{{ item }}"
    state: "directory"
  with_items:
    - "/var/lib/php/session"
    - "/var/lib/php/wsdlcache"
  when: webService|default("") == "httpd"

- name: PHP | RedHat | Create log directories nginx
  file:
    group: "nginx"
    owner: "nginx"
    mode: "0755"
    path: "{{ item }}"
    state: "directory"
  with_items:
    - "{{ fpmPhp56LogLocation }}"
    - "{{ fpmPhp70LogLocation }}"
    - "{{ fpmPhp71LogLocation }}"
    - "{{ fpmPhp72LogLocation }}"
    - "{{ fpmPhp73LogLocation }}"
    - "{{ fpmPhp74LogLocation }}"
    - "{{ fpmPhp80LogLocation }}"
    - "{{ fpmPhp81LogLocation }}"
    - "{{ fpmPhp82LogLocation }}"
  when: webService|default("") == "nginx"

- name: PHP | RedHat | Create php session folder nginx
  file:
    group: "nginx"
    owner: "nginx"
    mode: "0755"
    path: "{{ item }}"
    state: "directory"
  with_items:
    - "/var/lib/php/session"
    - "/var/lib/php/wsdlcache"
  when: webService|default("") == "nginx"
