---

- name: PHP | RedHat | Create folder
  file:
    mode: "0755"
    path: "{{ phpRedHatCGIBinLocation }}"
    state: "directory"

- name: PHP | RedHat | config remi repo
  include_role:
    name: "ggiinnoo.remi_repo"
  vars:
    remiCentosRepoList:
      - name: "{{ item }}"
        state: enable
  with_items:
    - "{{ phpRedHatPhpRedHatremiRepo }}"

- name: PHP | RedHat | Generate full list to install
  set_fact:
    phpItems: "{{ php56.packages|default([]) + php70.packages|default([]) + php71.packages|default([]) + php72.packages|default([]) + php73.packages|default([]) + php74.packages|default([]) + php80.packages|default([]) + php81.packages|default([]) + php82.packages|default([]) }}"

- name: PHP | RedHat | Install php items
  yum:
    name: "{{ phpItems }}"
    state: "installed"
